# Generated by Django 3.2.3 on 2021-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_affiliate_res',
            field=models.BooleanField(default=False),
        ),
    ]
