# Generated by Django 3.2.3 on 2021-10-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_search_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
