# Generated by Django 3.2.6 on 2021-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
