# Generated by Django 3.2.3 on 2021-12-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_is_affiliate_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_affiliate_res',
        ),
    ]
