# Generated by Django 3.2.6 on 2021-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_res_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_pos_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_pos_pw',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
