# Generated by Django 3.2.3 on 2021-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_is_affiliate_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_reservable_res',
            field=models.BooleanField(default=False),
        ),
    ]
