# Generated by Django 3.2.3 on 2021-12-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_is_reservable_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='is_reservable_res',
            new_name='is_reservable_r',
        ),
    ]
