# Generated by Django 3.2.6 on 2022-01-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220113_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResCouponLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('res_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.rescoupon')),
            ],
        ),
    ]
