# Generated by Django 3.2.6 on 2021-12-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_is_reservable_res_restaurant_is_reservable_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.BooleanField(default=True)),
                ('coupon_content', models.CharField(max_length=30)),
                ('coupon_count', models.IntegerField(default=0)),
                ('coupone_start_dttm', models.DateTimeField(auto_now_add=True)),
                ('coupone_end_dttm', models.DateTimeField(auto_now_add=True)),
                ('coupone_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
