# Generated by Django 3.2.6 on 2021-12-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rescoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescoupon',
            old_name='coupone_create_dttm',
            new_name='coupon_create_dttm',
        ),
        migrations.RenameField(
            model_name='rescoupon',
            old_name='coupone_end_dttm',
            new_name='coupon_end_dttm',
        ),
        migrations.RenameField(
            model_name='rescoupon',
            old_name='coupone_start_dttm',
            new_name='coupon_start_dttm',
        ),
    ]
