# Generated by Django 3.2.6 on 2021-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20211217_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_breaktime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_break_end_tm',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_break_start_tm',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_close_tm',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_open_days',
            field=models.JSONField(default={'0': {'name': '월요일', 'state': False}, '1': {'name': '화요일', 'state': False}, '2': {'name': '수요일', 'state': False}, '3': {'name': '목요일', 'state': False}, '4': {'name': '금요일', 'state': False}, '5': {'name': '토요일', 'state': False}, '6': {'name': '일요일', 'state': False}}),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_open_tm',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
