# Generated by Django 3.2.6 on 2021-12-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20211220_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_content', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('notice_create_dttm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
