# Generated by Django 3.2.6 on 2022-01-20 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usercoupon_user_coupon_key'),
        ('restaurant', '0008_auto_20220120_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescouponlog',
            name='user_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usercoupon'),
        ),
    ]
