# Generated by Django 3.2.6 on 2022-02-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_rescouponlog_user_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=30)),
                ('region_res', models.ManyToManyField(blank=True, null=True, to='restaurant.Restaurant')),
            ],
        ),
    ]
