# Generated by Django 3.2.6 on 2021-12-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_resnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='res_open_days',
        ),
    ]
