# Generated by Django 3.2.6 on 2021-12-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_restaurant_res_open_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_open_days',
            field=models.JSONField(default={'week_0': {'name': '월요일', 'state': False}, 'week_1': {'name': '화요일', 'state': False}, 'week_2': {'name': '수요일', 'state': False}, 'week_3': {'name': '목요일', 'state': False}, 'week_4': {'name': '금요일', 'state': False}, 'week_5': {'name': '토요일', 'state': False}, 'week_6': {'name': '일요일', 'state': False}}),
        ),
    ]
