# Generated by Django 3.2.6 on 2022-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_rep_menu',
            field=models.ManyToManyField(blank=True, related_name='restaurant_rep', to='restaurant.Menu'),
        ),
    ]
