# Generated by Django 3.2.6 on 2022-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurant_res_rep_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
    ]
