# Generated by Django 3.2.6 on 2022-02-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_menu_is_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='res_rep_menu',
        ),
    ]
