# Generated by Django 3.2.6 on 2022-02-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_restaurant_res_rep_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_res',
            field=models.ManyToManyField(blank=True, null=True, related_name='region_res', to='restaurant.Restaurant'),
        ),
    ]
