# Generated by Django 3.2.3 on 2021-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(default='title', max_length=30)),
                ('notice_content', models.TextField(blank=True, null=True)),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSourceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_title', models.CharField(default='license_title', max_length=30)),
                ('license_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservePopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_title', models.CharField(default='예약 규정', max_length=30)),
                ('popup_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
