# Generated by Django 3.2.3 on 2021-10-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_opensourcelicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opensourcelicense',
            old_name='notice_content',
            new_name='license_content',
        ),
        migrations.RenameField(
            model_name='opensourcelicense',
            old_name='notice_title',
            new_name='license_title',
        ),
    ]
