# Generated by Django 3.2.3 on 2021-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20211005_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservePopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_title', models.CharField(default='예약 규정', max_length=30)),
                ('popup_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
