# Generated by Django 3.2.6 on 2022-01-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_res_pos_time'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='res_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
