# Generated by Django 3.2.3 on 2021-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manner_rank',
            field=models.IntegerField(default=0),
        ),
    ]
