# Generated by Django 3.2.6 on 2021-12-15 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rescoupon'),
        ('accounts', '0002_user_manner_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_point', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupone_start_dttm', models.DateTimeField(auto_now_add=True)),
                ('coupone_end_dttm', models.DateTimeField(auto_now_add=True)),
                ('coupone_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('res_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.rescoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StampLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_own', models.IntegerField(default=0)),
                ('stamp_content', models.CharField(max_length=30)),
                ('stamp_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userstamp')),
            ],
        ),
    ]
