# Generated by Django 3.2.6 on 2022-01-17 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_res_pos_time'),
        ('accounts', '0002_alarm_res_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='res_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
