# Generated by Django 3.2.6 on 2022-01-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220117_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_ccoupon_content',
            new_name='user_coupon_content',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_ccoupon_count',
            new_name='user_coupon_count',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_ccoupon_create_dttm',
            new_name='user_coupon_create_dttm',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_ccoupon_end_dttm',
            new_name='user_coupon_end_dttm',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_ccoupon_start_dttm',
            new_name='user_coupon_start_dttm',
        ),
    ]
