# Generated by Django 3.2.6 on 2021-12-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rescoupon'),
        ('accounts', '0003_stamplog_usercoupon_userstamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStampApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_point', models.IntegerField(default=0)),
                ('is_stamp', models.BooleanField(default=False)),
                ('stamp_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
