# Generated by Django 3.2.3 on 2021-10-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userfcmtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfcmtoken',
            old_name='token',
            new_name='fcm_token',
        ),
    ]
