# Generated by Django 3.2.3 on 2021-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_res_search_name'),
        ('accounts', '0003_userfcmclienttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='menu_cannoteat',
            field=models.ManyToManyField(blank=True, to='restaurant.MenuCannotEat'),
        ),
    ]
