# Generated by Django 3.2.6 on 2021-12-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userstampapply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
