# Generated by Django 3.2.6 on 2022-01-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220119_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_coupon_count',
            new_name='user_coupon_state',
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user_coupon_end_dttm',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user_coupon_start_dttm',
            field=models.DateTimeField(),
        ),
    ]
