# Generated by Django 3.2.6 on 2022-01-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220119_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='user_coupon_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
