# Generated by Django 3.2.3 on 2021-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resreservationrequest_res_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resreservationrequest',
            name='res_deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resreservationrequest',
            name='res_expect_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
