# Generated by Django 3.2.6 on 2021-12-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20211217_1609'),
        ('accounts', '0005_delete_usercoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_coupon_type', models.BooleanField(default=True)),
                ('user_ccoupon_count', models.BooleanField(default=False)),
                ('user_ccoupon_content', models.CharField(max_length=30)),
                ('user_ccoupon_start_dttm', models.DateTimeField(auto_now_add=True)),
                ('user_ccoupon_end_dttm', models.DateTimeField(auto_now_add=True)),
                ('user_ccoupon_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCouponApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coupon', models.BooleanField(default=False)),
                ('coupon_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usercoupon')),
            ],
        ),
    ]
