# Generated by Django 3.2.6 on 2022-01-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usercoupon_user_coupon_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='user_coupon_key',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
