# Generated by Django 3.2.3 on 2021-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resreservationrequest',
            name='res_state',
            field=models.CharField(default='승인 대기', max_length=30),
        ),
    ]
