# Generated by Django 3.2.6 on 2021-12-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usercoupon_usercouponapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='resreservationrequest',
            name='is_arrived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='resreservationrequest',
            name='is_noshow',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
