# Generated by Django 3.2.6 on 2021-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211221_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='resreservationrequest',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
