# Generated by Django 3.2.6 on 2022-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usercoupon_user_coupon_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='res_state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
