# Generated by Django 3.2.6 on 2022-02-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_region'),
        ('accounts', '0008_alarm_res_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.region'),
        ),
    ]
